features:
  # Pitch characteristics
  release_speed: numeric
  release_pos_x: numeric
  release_pos_z: numeric
  release_spin_rate: numeric
  spin_axis: numeric
  release_extension: numeric
  pfx_x: numeric
  pfx_z: numeric
  plate_x: numeric
  plate_z: numeric

  # situation
  balls: numeric
  strikes: numeric

  # pitcher info
  p_throws: categorical

  # batter info
  stand: categorical
  sz_top: numeric
  sz_bot: numeric


keys:
  - game_pk
  - at_bat_number
  - pitch_number

# For testing mainly
aux_cols:
  - description

train_data_path: ./data/2023_data.parquet
split_seed: 212
morphers_path: ./data/morphers.yaml

morpher_dispatch:
  numeric: RankScaler
  categorical: Integerizer

model_params:
  embedding_size: 128
  mask_p: 0.5
  masking_strategy: learned
  projection_size: 32
  tr_nhead: 8
  tr_dim_ff: 1024
  tr_n_layers: 4
  proj_n_layers: 1
  lr: 0.0001
  weight_decay: 0.01
  loss_type: Matroshka twins
  loss_params:
    lambda_: 10
    # Must match projection_size
    max_size: 32
    # Highest value should match max_size
    m: [2, 4, 8, 16, 32]

training_params:
  batch_size: 2048
  epochs: 20
  precision: 16-true

mlflow_experiment: complementary_masking
