experiment_name: balls_and_strikes

source_checkpoint: logs/pretraining/version_2/checkpoints/epoch=14-step=2115.ckpt

targets:
  - [type, categorical, {}]

keys:
  - game_pk
  - at_bat_number
  - pitch_number

# For testing mainly
aux_cols:
  - description

train_data_path: ./data/2023_data.parquet
split_seed: 212
morphers_path: ./data/morphers.yaml

morpher_dispatch:
  numeric: Normalizer
  categorical: Integerizer

predictor_head_params:
  name: barlow_twins
  target_column: type
  embedding_size: 16
  predictor_dropout: 0.1
  n_layers: 4
  bt_loss_params:
    lambda_: 10
  alpha: 0.01
  lr: 0.0001
  weight_decay: 0.01
  

training_params:
  batch_size: 4096
  epochs: 10
  frozen_epochs: 10
  precision: 16-mixed
