features:
  # Pitch characteristics
  release_speed: numeric
  release_pos_x: numeric
  release_pos_z: numeric
  release_spin_rate: numeric
  spin_axis: numeric
  release_extension: numeric
  pfx_x: numeric
  pfx_z: numeric
  plate_x: numeric
  plate_z: numeric

  # situation
  balls: numeric
  strikes: numeric

  # pitcher info
  p_throws: categorical

  # batter info
  stand: categorical
  sz_top: numeric
  sz_bot: numeric

keys:
  - game_pk
  - at_bat_number
  - pitch_number

# For testing mainly
aux_cols:
  - pitch_type

split_seed: 212
train_data_path: ./data/2023_data.parquet
mlflow_experiment: linear_probes

model_source:
  checkpoint_name: epoch=5-step=1698
  run_id: e31b30f3dab7418c87e1f037a150e2a4

model_params:
  n_layers: 1
  targets:
    - fastball
    - curveball
    - slider
    - changeup
  lr: 0.001
  weight_decay: 0.01

training_params:
  batch_size: 128
  epochs: 16
