features:
  # Pitch characteristics
  release_speed: numeric
  release_pos_x: numeric
  release_pos_z: numeric
  release_spin_rate: numeric
  spin_axis: numeric
  release_extension: numeric
  pfx_x: numeric
  pfx_z: numeric
  plate_x: numeric
  plate_z: numeric

  # situation
  balls: numeric
  strikes: numeric

  # pitcher info
  p_throws: categorical

  # batter info
  stand: categorical
  sz_top: numeric
  sz_bot: numeric

keys:
  - game_pk
  - at_bat_number
  - pitch_number

# For testing mainly
aux_cols:
  - pitch_type

split_seed: 212
train_data_path: ./data/2023_data.parquet
mlflow_experiment: linear_probes

model_source:
  checkpoint_name: epoch=19-step=5660
  # Sometimes overwritten by a command-line argument.
  run_id: 8b69f950dceb4cb5b7b8f5a5a8e83cc2

# This has to match the source run's info. It would be better
# to reconstruct it somehow.
morpher_dispatch:
  numeric: RankScaler
  categorical: Integerizer

model_params:
  n_layers: 1
  targets:
    - fastball
    - curveball
    - slider
    - changeup
  lr: 0.001
  weight_decay: 0.01

training_params:
  batch_size: 128
  epochs: 16
  # It's possible you'll want to log a model for testing later.
  log_model: false
