features:
  # Pitch characteristics
  release_speed: numeric
  release_pos_x: numeric
  release_pos_z: numeric
  release_spin_rate: numeric
  spin_axis: numeric
  release_extension: numeric
  pfx_x: numeric
  pfx_z: numeric
  plate_x: numeric
  plate_z: numeric

  # situation
  balls: numeric
  strikes: numeric

  # pitcher info
  p_throws: categorical

  # batter info
  stand: categorical
  sz_top: numeric
  sz_bot: numeric

keys:
  - game_pk
  - at_bat_number
  - pitch_number

split_seed: 212
train_data_path: ./data/2023_data.parquet

model_source:
  checkpoint_name: epoch=5-step=1698
  run_id: f28d8085343942c381c60b73c7822e42

# This has to match the source run's info. It would be better
# to reconstruct it somehow.
morpher_dispatch:
  numeric: RankScaler
  categorical: Integerizer
